---
# This is the default file ansible-builder looks for to create a build context.

version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'ansible-automation-platform-24/ee-supported-rhel8:latest'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

