---
# Requirements file for the ansible modules.
# points to a valid requirements file for the ansible-galaxy collection install -r ... command
# Keep adding your collections here

collections:
  - name: f5networks.f5_modules
    source: https://github.com/F5Networks/f5-ansible-f5modules#ansible_collections/f5networks/f5_modules
    type: git
    version: devel
  - name: community.general
  - name: awx.awx
  - name: infoblox.nios_modules
  - name: infra.controller_configuration
  - name: containers.podman